language: ruby
sudo: false
cache: bundler
bundler_args: ""
branches:
  only: [master]

rvm:
  - 2.0.0
  - 2.1.8
  - 2.2.4
  - 2.3.0

gemfile:
 - gemfiles/rails32.gemfile
 - gemfiles/rails41.gemfile
 - gemfiles/rails42.gemfile

script: bundle exec rake test
